fetchNetwork:
  # type must be explicitely specifed for forward compatibility.
  # e.g. "kubernetes" could be an alternative lookup type.
  type: webhook
  # Webhook lookup. 
  webhook:
    url: https://api6.ipify.org?format=json
  # postTransform mutates the lookup results 
  # into a parseable IP CIDR.
  # If the results is already a valid CIDR,
  # postTransform can be left empty.
  postTransformations:
    - type: jsonpath
      jsonpath: '{.ip}'
    - type: format
      format: "%s/64"
allocateSubnets: # no support for ip pools of n amount of ips. 
  - name: public-ipv6-kube-apiserver
    netmask: /128 # parseable
resourceMutations:
  - subjectQuery:
      group: ""
      version: ""
      kind: ""
      selector: {}
    # fieldSelector in jsonpath notation.
    fieldSelector: ""
    # subnetName must be one of the allocated subnets defined above.
    subnetName: public-ipv6-kube-apiserver
